name: Pull Request CI
on:
  pull_request:
    branches:
      - 1.9.x
      - 1.x
      - 2.x
      - 3.x
      - 4.x

jobs:
  build:
    runs-on: ${{ matrix.os }}-jdk${{ matrix.java }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['11', '21']
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Version Info
        run: mvn -version
      - name: Build with Maven
        run: mvn -B package --file pom.xml
